### ISSUE TITLE
Log out by itself does not work 

### ISSUE THREAD

**Issue by karinocheretny** [CS-461-nilsstreedain/classroom-polling#42]
when clicking log out server receives: 
ERROR:     jwt must be provided
JsonWebTokenError: jwt must be provided
    at Object.module.exports [as verify] (C:\Users\19713\source\repos\classroom-polling\node_modules\jsonwebtoken\verify.js:60:17)
    at Object.decode (C:\Users\19713\source\repos\classroom-polling\server\lib\jwt_utils.js:8:16)
    at requireAuthentication (C:\Users\19713\source\repos\classroom-polling\server\lib\auth.js:51:35)
    at Layer.handle [as handle_request] (C:\Users\19713\source\repos\classroom-polling\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\19713\source\repos\classroom-polling\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\19713\source\repos\classroom-polling\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\19713\source\repos\classroom-polling\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\19713\source\repos\classroom-polling\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\19713\source\repos\classroom-polling\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\19713\source\repos\classroom-polling\node_modules\express\lib\router\index.js:280:10)

clicking 'log out' and then 'profile' makes the user log out. Otherwise, log out by itself fails. 

<img width="759" alt="Screenshot 2023-11-26 172323" src="https://github.com/CS-461-nilsstreedain/classroom-polling/assets/102639509/806ceb7d-2a59-43fb-a3a0-5ad8d5690066">

**Comment by Justin-Fernbaugh** [comment]
Just a heads up, I diagnosed this a bit. This is a ReactJS issue; The href points to '/login' before logging in and after logging in it still points to '/login' when href SHOULD point to '/logout'.

just to clarify when you manually type the '/logout' path it works fine so updating the path will fix it.

**Comment by nilsstreedain** [comment]
Close due to #127
